[New Feature] Login/signup
upathorg/profile-frontend pull request #1
Opened 2020-09-15 18:41 UTC by jasonn0118

This is Login/Signup page feature is done initially.

2020-09-16 02:31 UTC, yoniakabecky requested changes
You import bootstrap css in the `src/routes/index.js` but not using it. (I think you are using some tailwindSCC classes🤔)

If we are importing that or tailwindCSS, better to use those classes instead of making new classes, I think.
`.page-wrapper` -> `tailwind: flex` or `bootstrap: d-flex`
`.logo-btn-wrapper` -> `tailwind: justify-around` or `bootstrap: justify-content-around`
something like this?

2020-09-16 02:31 UTC, yoniakabecky commented on src/routes/Login.css
> +}
better to align indent?

2020-09-16 02:31 UTC, yoniakabecky commented on src/routes/Login.css
> +  padding: 10rem;
top and bottom padding is causing bottom space...

![image](https://user-images.githubusercontent.com/46503638/93284381-742d6880-f787-11ea-96dd-5e5a63c60fb4.png)

2020-09-16 21:20 UTC, jasonn0118 commented on src/routes/components/utils/sharedButtons/AuthButton.css
> +.linkedin-btn:hover {
the reason I put Bootstrap on the index.js file is for wrapping all components under Bootstrap css.
[Bootstrap Documentation](https://react-bootstrap.github.io/getting-started/introduction)

And we will convert css file to Sass file after integration. (From my understanding on last meeting with Mike)

2020-09-16 21:21 UTC, jasonn0118 commented on src/routes/components/utils/sharedButtons/AuthButton.css
> +.linkedin-btn:hover {
And yes!
I agree when we use Sass it will be better structure!

2020-09-16 21:22 UTC, jasonn0118 commented on src/routes/Login.css
> +}
I think it is better to align with where code started.

2020-09-16 21:23 UTC, jasonn0118 commented on src/routes/Login.css
> +  padding: 10rem;
Oh thanks for checking

2020-09-16 23:58 UTC, yoniakabecky commented on src/routes/Login.css
> +}
@jasonn0118 
Sorry, my bad. I mean, better to use spacing 2 here.
Cause only this class is using 4 spaces indent.

2020-09-17 17:07 UTC, yoniakabecky approved these changes

2020-09-17 17:36 UTC, merged